#!/usr/bin/env node
/* ---------------------------------------------------------------------------
   Fulfil one request, in two commands with nothing retyped.

   THE PROBLEM THIS SOLVES. The old flow was: copy the research command out of
   Slack and run it; find and read the rendered brief; then type a release
   command that repeated the recipient's name, email and company — values that
   were already sitting in the Slack message. That last step is where a typo
   sends a client's analysis to the wrong address, and it is entirely avoidable:
   the intake is known at request time, so it should travel with the run rather
   than through the operator's clipboard twice.

   So the first pass writes `intake.json` into the run directory alongside the
   evidence, and the second pass reads it. The Slack alert carries one line for
   each:

     npm run fulfil -- --domain acme.com --email dana@acme.com \
       --name "Dana Whitfield" --company "Acme" \
       --category "..." --peer other.com

     npm run fulfil -- --domain acme.com --release

   THE HUMAN GATE IS THE DEFAULT. The first pass stops after rendering and
   tells you where to read it. Nothing is uploaded, nothing is emailed, and
   `--release` is a separate decision made after reading. A flow where one
   command both generates and sends would make the review optional, and the
   review is the product.
--------------------------------------------------------------------------- */
import { spawn } from 'node:child_process';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const SITE_ROOT = resolve(new URL('.', import.meta.url).pathname, '..');
const EXPOSURE_ROOT = resolve(SITE_ROOT, '../../tools/exposure');

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] && !process.argv[i + 1].startsWith('--')
    ? process.argv[i + 1]
    : fallback;
};
const flag = (name) => process.argv.includes(`--${name}`);
const all = (name) => {
  const out = [];
  process.argv.forEach((a, i) => {
    if (a === `--${name}` && process.argv[i + 1]) out.push(process.argv[i + 1]);
  });
  return out;
};

const domain = arg('domain');
if (!domain) {
  console.error(`Usage:
  Run it:      npm run fulfil -- --domain <domain> --email <them> --name "<Name>" \\
                 --company "<Co>" --category "<one-liner>" [--peer <domain>]...
  Release it:  npm run fulfil -- --domain <domain> --release [--send]

Flags:
  --release    upload, verify and (with --send) email the link
  --send       actually email it. Without this, --release prints the link
  --force      release below the coverage threshold, having read it
  --run <id>   act on a specific run instead of the newest
  --budget <n> pipeline spend ceiling for this run, in dollars
`);
  process.exit(1);
}

const runsDir = join(EXPOSURE_ROOT, 'runs', domain.replace(/[^a-z0-9.-]/gi, '_'));

/** Newest run for this domain, or null. */
async function newestRun() {
  try {
    const entries = await readdir(runsDir);
    return entries.filter((e) => !e.startsWith('.')).sort().at(-1) ?? null;
  } catch {
    return null;
  }
}

/** Run a command, inheriting stdio so the pipeline's own output is the output. */
function run(cmd, args, cwd) {
  return new Promise((done, fail) => {
    const p = spawn(cmd, args, { cwd, stdio: 'inherit', shell: false });
    p.on('error', fail);
    p.on('close', (code) => (code === 0 ? done() : fail(new Error(`${cmd} exited ${code}`))));
  });
}

/* ------------------------------ release ------------------------------- */

if (flag('release')) {
  const runId = arg('run', await newestRun());
  if (!runId) {
    console.error(`No runs for ${domain}. Generate one first (drop --release).`);
    process.exit(3);
  }

  /* The intake the first pass recorded. Without it we would be asking the
     operator to retype an email address, which is the mistake this exists to
     prevent — so we stop rather than prompt. */
  let intake;
  try {
    intake = JSON.parse(await readFile(join(runsDir, runId, 'intake.json'), 'utf8'));
  } catch {
    console.error(
      `No intake.json in ${join(runsDir, runId)}.\n` +
        'That run predates this script, or was generated by hand. Release it with\n' +
        '`npm run release` and pass the recipient explicitly.\n'
    );
    process.exit(4);
  }

  const relArgs = [
    '--domain', domain,
    '--run', runId,
    '--email', intake.email,
    '--name', intake.name,
    '--company', intake.company,
    '--verify',
  ];
  if (flag('force')) relArgs.push('--force');
  if (flag('send')) relArgs.push('--send');

  console.error(
    `\nReleasing ${domain} run ${runId} to ${intake.email}` +
      `${flag('send') ? '' : '  (printing only — add --send to email it)'}\n`
  );
  await run('node', ['--experimental-strip-types', 'scripts/release-report.mjs', ...relArgs], SITE_ROOT);
  process.exit(0);
}

/* ------------------------------- generate ----------------------------- */

const email = arg('email');
const name = arg('name');
const company = arg('company');
const category = arg('category');

const missing = [
  !email && '--email',
  !name && '--name',
  !company && '--company',
  !category && '--category',
].filter(Boolean);
if (missing.length) {
  console.error(`Missing ${missing.join(', ')}. Copy the whole line from the Slack alert.`);
  process.exit(2);
}

const reportArgs = ['--experimental-strip-types', 'src/cli.ts', 'report', domain, '--quiet',
  '--company', company, '--category', category];
for (const peer of all('peer')) reportArgs.push('--peer', peer);
const trigger = arg('trigger');
if (trigger) reportArgs.push('--trigger', trigger);
const budget = arg('budget');
if (budget) reportArgs.push('--budget', budget);

const before = await newestRun();
await run('node', reportArgs, EXPOSURE_ROOT);

const runId = await newestRun();
if (!runId || runId === before) {
  console.error('\nThe pipeline produced no new run directory. Nothing to release.');
  process.exit(5);
}

/* Record the intake with the run, so releasing needs nothing retyped. */
await writeFile(
  join(runsDir, runId, 'intake.json'),
  `${JSON.stringify({ name, email, company, domain, category, peers: all('peer'), recordedAt: runId }, null, 2)}\n`
);

const coverage = JSON.parse(await readFile(join(runsDir, runId, 'coverage.json'), 'utf8'));
const pct = Math.round(coverage.score * 100);

console.error(`
──────────────────────────────────────────────────────────────
  Read it before it goes anywhere.

    ${join(runsDir, runId, 'report.html')}

  Coverage ${pct}%${coverage.sufficient ? '' : `  BELOW THRESHOLD — ${coverage.shortfalls.join('; ')}`}
  For ${name} <${email}> at ${company}

  Then:
    npm run fulfil -- --domain ${domain} --release           # link only
    npm run fulfil -- --domain ${domain} --release --send    # email it${coverage.sufficient ? '' : '\n    …add --force if you have read it and disagree with the threshold'}
──────────────────────────────────────────────────────────────
`);
